# Generated by Django 5.2.9 on 2025-12-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ignored_skills',
            field=models.ManyToManyField(blank=True, related_name='ignored_by', to='skills.skill'),
        ),
    ]
