# Generated by Django 5.2.9 on 2025-12-25 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='creator',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='created_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='skills', to='skills.file'),
        ),
        migrations.AddField(
            model_name='pause',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='node',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='skillprogress',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='skillprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tree',
            name='goal_skill',
            field=models.ForeignKey(help_text='The final skill that completes this tree', on_delete=django.db.models.deletion.PROTECT, related_name='goal_of_trees', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='node',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='skills.tree'),
        ),
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together={('from_node', 'to_node')},
        ),
        migrations.AlterUniqueTogether(
            name='pause',
            unique_together={('skill', 'time')},
        ),
        migrations.AlterUniqueTogether(
            name='skillprogress',
            unique_together={('user', 'skill')},
        ),
    ]
