# Generated by Django 5.2.9 on 2025-12-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pause',
            name='clipboard',
            field=models.TextField(blank=True, help_text='Text to copy to clipboard when button is clicked'),
        ),
        migrations.AddConstraint(
            model_name='pause',
            constraint=models.CheckConstraint(condition=models.Q(('attachment__isnull', False), models.Q(('clipboard', ''), _negated=True), _negated=True), name='pause_not_both_attachment_and_clipboard'),
        ),
    ]
