# Generated by Django 5.2.9 on 2025-12-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_add_clipboard_to_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='preview_config',
            field=models.JSONField(blank=True, default=dict, help_text='Config for preview: strudel={pattern}, animation={type}'),
        ),
        migrations.AddField(
            model_name='tree',
            name='preview_type',
            field=models.CharField(choices=[('strudel', 'Strudel Player'), ('animation', 'Custom Animation')], default='animation', max_length=20),
        ),
    ]
